### ISSUE TITLE
I got error when I used your model file "convnext_tf.py" and use trained with callback for model save. Is there model prior save model weight file or error from my side? Need your help and suggestions. Thank you. 

### ISSUE THREAD

**Issue by AIFahim** [sayakpaul/ConvNeXt-TF#6]
![2022-03-08_12-02](https://user-images.githubusercontent.com/33654834/157176824-172b086d-1e10-487a-b1dd-fc2cb1da4d4a.png)

**Comment by sayakpaul** [comment]
I need to see the full code to know why this error is coming.

**Comment by AIFahim** [comment]
[Code Link](https://ideone.com/4QQF64)
[Callback Link](https://ideone.com/NeVMYG)

Thanks for your response please check. Thanks.

**Comment by sayakpaul** [comment]
Please provide a Colab Notebook link that would allow me to reproduce the issue.

**Comment by AIFahim** [comment]
[Colab Notebook Link](https://colab.research.google.com/drive/1lEDhQMACF4HkpozJR5OCd3n6ISVL0n0X?usp=sharing)
In the output, you will find output exists. You can run all to reproduce the same error. Please the the following cell: 

![2022-03-08_14-43](https://user-images.githubusercontent.com/33654834/157200227-042b4c71-6c79-452a-8e44-bf8612758f95.png)

**Comment by sayakpaul** [comment]
It's probably best to open this issue in the Keras repository. There's a similar issue here: https://stackoverflow.com/questions/70739244/valueerror-unable-to-create-dataset-name-already-exists-while-saving-tensorfl.

**Comment by AIFahim** [comment]
Thanks but I tried with other models but didn't get this error.

**Comment by sayakpaul** [comment]
I see. Since the model definition itself is a bit contrived it's currently not possible for me to dig deeper. The easiest fix I can suggest is serializing the model as a SavedModel resource rather h5 file.

**Comment by AIFahim** [comment]
Thanks sayak for your response will check this hope to solve it anyhow. Thanks for your contribution.

**Comment by uranusx86** [comment]
The error is caused by missing `get_config()` and `from_config()` methods in `Class StochasticDepth`.
See [Tensorflow Guide](https://www.tensorflow.org/guide/keras/making_new_layers_and_models_via_subclassing#you_can_optionally_enable_serialization_on_your_layers).
