### ISSUE TITLE
Model arguments for get_convnext_model.

### ISSUE THREAD

**Issue by vafaei-ar** [sayakpaul/ConvNeXt-TF#8]
Hi there.

May you provide the arguments for "get_convnext_model" function to produce similar models to the lists here:
https://github.com/facebookresearch/ConvNeXt#results-and-pre-trained-models

In particular, I need them to generate "convnext_base_1k_224" and "convnext_xlarge_21k_1k_224".

**Comment by sayakpaul** [comment]
Refer here: https://github.com/sayakpaul/ConvNeXt-TF/blob/main/models/model_configs.py
